CREATE TABLE employees (
  employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name VARCHAR2(100)
);
INSERT INTO employees (employee_name) VALUES ('John Doe');
INSERT INTO employees (employee_name) VALUES ('Jane Smith');
INSERT INTO employees (employee_name) VALUES ('Michael Johnson');
INSERT INTO employees (employee_name) VALUES ('Emily Brown');
COMMIT;

SET SERVEROUTPUT ON;
DECLARE
    v_name VARCHAR2(30);
    -- Declare the cursor
    CURSOR cur_RRider IS
    SELECT first_name FROM employees
    WHERE employee_id < 105;
BEGIN
    OPEN cur_RRider;
    LOOP
        FETCH cur_RRider INTO v_name;
        DBMS_OUTPUT.PUT_LINE(v_name);
        EXIT WHEN cur_RRider%NOTFOUND;
    END LOOP;
    CLOSE cur_RRider;
END;
/